title: la'au ra'i le cange li'u
description: >-
  Lojban interpretations of Farmer Thaddeus's farm updates
baseurl: /lahau-rahi-le-cange-lihu
url: https://alxndr.github.io
logo: "/assets/images/logo.png"

remote_theme: "mmistakes/minimal-mistakes@4.24.0"
minimal_mistakes_skin: "dirt"

plugins:
  - jekyll-feed
  - jekyll-include-cache

kramdown:
 smart_quotes: ["apos", "apos", "quot", "quot"]
